In [3]:
import pandas as pd
df = pd.read_csv("Downloads/sales_raw.csv")
df

   Product Name   Quantity   Price       City
0        Shampoo        NaN   250.0  Bangalore
1        Perfume        4.0  3000.0    Chennai
2           Soap        3.0   250.0       Pune
3           Soap       18.0  3000.0  Bangalore
4     Toothpaste        NaN    50.0  Bangalore
5    Conditioner        NaN   180.0  Bangalore
6     Hair Serum        4.0  3000.0    Chennai
7     Hair Serum        NaN    50.0     Mumbai
8        Shampoo       13.0   500.0       Pune
9     Hair Serum       19.0   120.0    Chennai
10   Body Lotion       10.0   250.0    Chennai
11   Conditioner        NaN  1500.0  Bangalore
12    Hair Serum       12.0   500.0    Chennai
13       Perfume       18.0   180.0     Mumbai
14   Conditioner        9.0  1500.0    Chennai
15   Body Lotion        NaN  3000.0  Hyderabad
16       Shampoo        NaN   250.0     Mumbai
17   Conditioner       15.0   500.0  Bangalore
18   Body Lotion        NaN  3000.0       Pune
19   Conditioner       12.0   180.0       Pune
20    Toothpaste        3.0   120.0  Bangalore
21       Perfume       14.0  3000.0     Mumbai
22    Toothpaste        NaN    50.0    Chennai
23     Face Wash       11.0   500.0     Mumbai
24       Perfume       15.0   500.0       Pune
25       Perfume       17.0   500.0       Pune
26   Body Lotion        NaN   180.0       Pune
27          Soap        NaN     NaN    Chennai
28       Shampoo        NaN   250.0    Chennai
29   Body Lotion       19.0   120.0     Mumbai
30       Shampoo       18.0   180.0     Mumbai
31       Perfume        NaN   250.0       Pune
32   Body Lotion        NaN  1500.0     Mumbai
33    Toothpaste        4.0   250.0    Chennai
34    Hair Serum        1.0   250.0    Chennai
35       Shampoo        2.0   120.0    Chennai
36    Hair Serum        3.0   500.0     Mumbai
37   Body Lotion       18.0     NaN  Bangalore
38    Toothpaste       14.0   120.0    Chennai
39   Conditioner        NaN  3000.0     Mumbai
40          Soap        4.0  3000.0  Hyderabad
41       Shampoo        8.0   250.0       Pune
42    Toothpaste        NaN   180.0  Hyderabad
43    Toothpaste        8.0     NaN       Pune
44       Shampoo        2.0   120.0  Bangalore
45       Perfume        NaN     NaN  Bangalore
46   Conditioner        2.0  3000.0    Chennai
47   Conditioner        NaN   500.0     Mumbai
48    Toothpaste        5.0   500.0  Bangalore
49          Soap       19.0  1500.0    Chennai

In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0    Product Name   50 non-null     object
 1    Quantity       32 non-null     float64
 2    Price          46 non-null     float64
 3    City           50 non-null     object
dtypes: float64(2), object(2)
memory usage: 1.7+ KB
None

In [5]:
df.columns = df.columns.str.strip()

In [6]:
df

   Product Name  Quantity   Price       City
0       Shampoo       NaN   250.0  Bangalore
1       Perfume       4.0  3000.0    Chennai
2          Soap       3.0   250.0       Pune
3          Soap      18.0  3000.0  Bangalore
4    Toothpaste       NaN    50.0  Bangalore
5   Conditioner       NaN   180.0  Bangalore
6    Hair Serum       4.0  3000.0    Chennai
7    Hair Serum       NaN    50.0     Mumbai
8       Shampoo      13.0   500.0       Pune
9    Hair Serum      19.0   120.0    Chennai
10  Body Lotion      10.0   250.0    Chennai
11  Conditioner       NaN  1500.0  Bangalore
12   Hair Serum      12.0   500.0    Chennai
13      Perfume      18.0   180.0     Mumbai
14  Conditioner       9.0  1500.0    Chennai
15  Body Lotion       NaN  3000.0  Hyderabad
16      Shampoo       NaN   250.0     Mumbai
17  Conditioner      15.0   500.0  Bangalore
18  Body Lotion       NaN  3000.0       Pune
19  Conditioner      12.0   180.0       Pune
20   Toothpaste       3.0   120.0  Bangalore
21      Perfume      14.0  3000.0     Mumbai
22   Toothpaste       NaN    50.0    Chennai
23    Face Wash      11.0   500.0     Mumbai
24      Perfume      15.0   500.0       Pune
25      Perfume      17.0   500.0       Pune
26  Body Lotion       NaN   180.0       Pune
27         Soap       NaN     NaN    Chennai
28      Shampoo       NaN   250.0    Chennai
29  Body Lotion      19.0   120.0     Mumbai
30      Shampoo      18.0   180.0     Mumbai
31      Perfume       NaN   250.0       Pune
32  Body Lotion       NaN  1500.0     Mumbai
33   Toothpaste       4.0   250.0    Chennai
34   Hair Serum       1.0   250.0    Chennai
35      Shampoo       2.0   120.0    Chennai
36   Hair Serum       3.0   500.0     Mumbai
37  Body Lotion      18.0     NaN  Bangalore
38   Toothpaste      14.0   120.0    Chennai
39  Conditioner       NaN  3000.0     Mumbai
40         Soap       4.0  3000.0  Hyderabad
41      Shampoo       8.0   250.0       Pune
42   Toothpaste       NaN   180.0  Hyderabad
43   Toothpaste       8.0     NaN       Pune
44      Shampoo       2.0   120.0  Bangalore
45      Perfume       NaN     NaN  Bangalore
46  Conditioner       2.0  3000.0    Chennai
47  Conditioner       NaN   500.0     Mumbai
48   Toothpaste       5.0   500.0  Bangalore
49         Soap      19.0  1500.0    Chennai

In [7]:
print(df.isna().sum())

Product Name     0
Quantity        18
Price            4
City             0
dtype: int64

In [8]:
df["Quantity"] = df["Quantity"].fillna(0)

In [9]:
df

   Product Name  Quantity   Price       City
0       Shampoo       0.0   250.0  Bangalore
1       Perfume       4.0  3000.0    Chennai
2          Soap       3.0   250.0       Pune
3          Soap      18.0  3000.0  Bangalore
4    Toothpaste       0.0    50.0  Bangalore
5   Conditioner       0.0   180.0  Bangalore
6    Hair Serum       4.0  3000.0    Chennai
7    Hair Serum       0.0    50.0     Mumbai
8       Shampoo      13.0   500.0       Pune
9    Hair Serum      19.0   120.0    Chennai
10  Body Lotion      10.0   250.0    Chennai
11  Conditioner       0.0  1500.0  Bangalore
12   Hair Serum      12.0   500.0    Chennai
13      Perfume      18.0   180.0     Mumbai
14  Conditioner       9.0  1500.0    Chennai
15  Body Lotion       0.0  3000.0  Hyderabad
16      Shampoo       0.0   250.0     Mumbai
17  Conditioner      15.0   500.0  Bangalore
18  Body Lotion       0.0  3000.0       Pune
19  Conditioner      12.0   180.0       Pune
20   Toothpaste       3.0   120.0  Bangalore
21      Perfume      14.0  3000.0     Mumbai
22   Toothpaste       0.0    50.0    Chennai
23    Face Wash      11.0   500.0     Mumbai
24      Perfume      15.0   500.0       Pune
25      Perfume      17.0   500.0       Pune
26  Body Lotion       0.0   180.0       Pune
27         Soap       0.0     NaN    Chennai
28      Shampoo       0.0   250.0    Chennai
29  Body Lotion      19.0   120.0     Mumbai
30      Shampoo      18.0   180.0     Mumbai
31      Perfume       0.0   250.0       Pune
32  Body Lotion       0.0  1500.0     Mumbai
33   Toothpaste       4.0   250.0    Chennai
34   Hair Serum       1.0   250.0    Chennai
35      Shampoo       2.0   120.0    Chennai
36   Hair Serum       3.0   500.0     Mumbai
37  Body Lotion      18.0     NaN  Bangalore
38   Toothpaste      14.0   120.0    Chennai
39  Conditioner       0.0  3000.0     Mumbai
40         Soap       4.0  3000.0  Hyderabad
41      Shampoo       8.0   250.0       Pune
42   Toothpaste       0.0   180.0  Hyderabad
43   Toothpaste       8.0     NaN       Pune
44      Shampoo       2.0   120.0  Bangalore
45      Perfume       0.0     NaN  Bangalore
46  Conditioner       2.0  3000.0    Chennai
47  Conditioner       0.0   500.0     Mumbai
48   Toothpaste       5.0   500.0  Bangalore
49         Soap      19.0  1500.0    Chennai

In [10]:
df["Price"] = df["Price"].fillna(0)

In [11]:
df

   Product Name  Quantity   Price       City
0       Shampoo       0.0   250.0  Bangalore
1       Perfume       4.0  3000.0    Chennai
2          Soap       3.0   250.0       Pune
3          Soap      18.0  3000.0  Bangalore
4    Toothpaste       0.0    50.0  Bangalore
5   Conditioner       0.0   180.0  Bangalore
6    Hair Serum       4.0  3000.0    Chennai
7    Hair Serum       0.0    50.0     Mumbai
8       Shampoo      13.0   500.0       Pune
9    Hair Serum      19.0   120.0    Chennai
10  Body Lotion      10.0   250.0    Chennai
11  Conditioner       0.0  1500.0  Bangalore
12   Hair Serum      12.0   500.0    Chennai
13      Perfume      18.0   180.0     Mumbai
14  Conditioner       9.0  1500.0    Chennai
15  Body Lotion       0.0  3000.0  Hyderabad
16      Shampoo       0.0   250.0     Mumbai
17  Conditioner      15.0   500.0  Bangalore
18  Body Lotion       0.0  3000.0       Pune
19  Conditioner      12.0   180.0       Pune
20   Toothpaste       3.0   120.0  Bangalore
21      Perfume      14.0  3000.0     Mumbai
22   Toothpaste       0.0    50.0    Chennai
23    Face Wash      11.0   500.0     Mumbai
24      Perfume      15.0   500.0       Pune
25      Perfume      17.0   500.0       Pune
26  Body Lotion       0.0   180.0       Pune
27         Soap       0.0     0.0    Chennai
28      Shampoo       0.0   250.0    Chennai
29  Body Lotion      19.0   120.0     Mumbai
30      Shampoo      18.0   180.0     Mumbai
31      Perfume       0.0   250.0       Pune
32  Body Lotion       0.0  1500.0     Mumbai
33   Toothpaste       4.0   250.0    Chennai
34   Hair Serum       1.0   250.0    Chennai
35      Shampoo       2.0   120.0    Chennai
36   Hair Serum       3.0   500.0     Mumbai
37  Body Lotion      18.0     0.0  Bangalore
38   Toothpaste      14.0   120.0    Chennai
39  Conditioner       0.0  3000.0     Mumbai
40         Soap       4.0  3000.0  Hyderabad
41      Shampoo       8.0   250.0       Pune
42   Toothpaste       0.0   180.0  Hyderabad
43   Toothpaste       8.0     0.0       Pune
44      Shampoo       2.0   120.0  Bangalore
45      Perfume       0.0     0.0  Bangalore
46  Conditioner       2.0  3000.0    Chennai
47  Conditioner       0.0   500.0     Mumbai
48   Toothpaste       5.0   500.0  Bangalore
49         Soap      19.0  1500.0    Chennai

In [12]:
print(df.isna().sum())

Product Name    0
Quantity        0
Price           0
City            0
dtype: int64

In [13]:
df["Quantity"] = df["Quantity"].astype(int)

df["Price"] = df["Price"].astype(float)

In [14]:
df

   Product Name  Quantity   Price       City
0       Shampoo         0   250.0  Bangalore
1       Perfume         4  3000.0    Chennai
2          Soap         3   250.0       Pune
3          Soap        18  3000.0  Bangalore
4    Toothpaste         0    50.0  Bangalore
5   Conditioner         0   180.0  Bangalore
6    Hair Serum         4  3000.0    Chennai
7    Hair Serum         0    50.0     Mumbai
8       Shampoo        13   500.0       Pune
9    Hair Serum        19   120.0    Chennai
10  Body Lotion        10   250.0    Chennai
11  Conditioner         0  1500.0  Bangalore
12   Hair Serum        12   500.0    Chennai
13      Perfume        18   180.0     Mumbai
14  Conditioner         9  1500.0    Chennai
15  Body Lotion         0  3000.0  Hyderabad
16      Shampoo         0   250.0     Mumbai
17  Conditioner        15   500.0  Bangalore
18  Body Lotion         0  3000.0       Pune
19  Conditioner        12   180.0       Pune
20   Toothpaste         3   120.0  Bangalore
21      Perfume        14  3000.0     Mumbai
22   Toothpaste         0    50.0    Chennai
23    Face Wash        11   500.0     Mumbai
24      Perfume        15   500.0       Pune
25      Perfume        17   500.0       Pune
26  Body Lotion         0   180.0       Pune
27         Soap         0     0.0    Chennai
28      Shampoo         0   250.0    Chennai
29  Body Lotion        19   120.0     Mumbai
30      Shampoo        18   180.0     Mumbai
31      Perfume         0   250.0       Pune
32  Body Lotion         0  1500.0     Mumbai
33   Toothpaste         4   250.0    Chennai
34   Hair Serum         1   250.0    Chennai
35      Shampoo         2   120.0    Chennai
36   Hair Serum         3   500.0     Mumbai
37  Body Lotion        18     0.0  Bangalore
38   Toothpaste        14   120.0    Chennai
39  Conditioner         0  3000.0     Mumbai
40         Soap         4  3000.0  Hyderabad
41      Shampoo         8   250.0       Pune
42   Toothpaste         0   180.0  Hyderabad
43   Toothpaste         8     0.0       Pune
44      Shampoo         2   120.0  Bangalore
45      Perfume         0     0.0  Bangalore
46  Conditioner         2  3000.0    Chennai
47  Conditioner         0   500.0     Mumbai
48   Toothpaste         5   500.0  Bangalore
49         Soap        19  1500.0    Chennai

In [16]:
from pathlib import Path

clean_file = Path("sales_clean.csv")

df.to_csv(
    clean_file,
    index=False
)

In [17]:
clean_file

WindowsPath('sales_clean.csv')

In [31]:
import json

summary = {

    "Total Rows": len(df),

    "Total Quantity": int(df["Quantity"].sum()),

    "Total Sales": float(
        (df["Quantity"] * df["Price"]).sum()
    ),

    "Average Price": float(
        df["Price"].mean()
    )
}

In [32]:
summary

{'Total Rows': 50,
 'Total Quantity': 324,
 'Total Sales': 247720.0,
 'Average Price': 834.0}

In [33]:
summary_file = Path("sales_summary.json")

with open(summary_file, "w") as file:

    json.dump(
        summary,
        file,
        indent=4
    )

In [34]:
from openpyxl import Workbook

wb = Workbook()

ws = wb.active

ws.title = "Sales Report"

In [35]:
headers = list(df.columns)

ws.append(headers)

In [36]:
from openpyxl.styles import Font

for cell in ws[1]:

    cell.font = Font(
        bold=True
    )

In [37]:
for row in df.itertuples(index=False):

    ws.append(row)

In [38]:
excel_file = Path("sales_report.xlsx")

wb.save(excel_file)