In [2]:
import pandas as pd
df = pd.read_csv("Downloads/orders_strings_dates.csv")
df.head()

,order_id,product_name,ship_address,order_date,ship_date
0,ORD-1001,smart watch,"282 MG Road, Chennai (TN)",2024-01-02,2024-01-08
1,ORD-1002,"monitor 24""!!","105 MG Road, Bengaluru (KA)",2024-01-09,2024-01-15
2,ORD-1003,laptop!!,"33 MG Road, Chennai (TN)",2024-02-07,2024-02-11
3,ORD-1004,webcam@@@,"518 MG Road, Chennai (TN)",2024-01-14,2024-01-16
4,ORD-1005,"monitor 24""!!","734 MG Road, Chennai (TN)",2024-02-05,2024-02-07

In [3]:
#Standardise product_name

df["product_name"] = (df["product_name"].str.strip()
                     .str.title()
                     .str.replace(r"[^A-Za-z0-9]", "",regex = True))

In [4]:
df.head()

   order_id product_name                 ship_address  order_date   ship_date
0  ORD-1001   SmartWatch    282 MG Road, Chennai (TN)  2024-01-02  2024-01-08
1  ORD-1002    Monitor24  105 MG Road, Bengaluru (KA)  2024-01-09  2024-01-15
2  ORD-1003       Laptop     33 MG Road, Chennai (TN)  2024-02-07  2024-02-11
3  ORD-1004       Webcam    518 MG Road, Chennai (TN)  2024-01-14  2024-01-16
4  ORD-1005    Monitor24    734 MG Road, Chennai (TN)  2024-02-05  2024-02-07

In [5]:
#Extract region code using Regex

df["region_code"] = df["ship_address"].str.extract(r"\((.*?)\)")
df.head()

,order_id,product_name,ship_address,order_date,ship_date,region_code
0,ORD-1001,SmartWatch,"282 MG Road, Chennai (TN)",2024-01-02,2024-01-08,TN
1,ORD-1002,Monitor24,"105 MG Road, Bengaluru (KA)",2024-01-09,2024-01-15,KA
2,ORD-1003,Laptop,"33 MG Road, Chennai (TN)",2024-02-07,2024-02-11,TN
3,ORD-1004,Webcam,"518 MG Road, Chennai (TN)",2024-01-14,2024-01-16,TN
4,ORD-1005,Monitor24,"734 MG Road, Chennai (TN)",2024-02-05,2024-02-07,TN

In [6]:
df["order_date"] = pd.to_datetime(df["order_date"])
df["ship_date"] = pd.to_datetime(df["ship_date"])

In [11]:
df["days_to_ship"] = (df["ship_date"] - df["order_date"]).dt.days
df.head()

,order_id,product_name,ship_address,order_date,ship_date,region_code,days_to_ship
0,ORD-1001,SmartWatch,"282 MG Road, Chennai (TN)",2024-01-02,2024-01-08,TN,6
1,ORD-1002,Monitor24,"105 MG Road, Bengaluru (KA)",2024-01-09,2024-01-15,KA,6
2,ORD-1003,Laptop,"33 MG Road, Chennai (TN)",2024-02-07,2024-02-11,TN,4
3,ORD-1004,Webcam,"518 MG Road, Chennai (TN)",2024-01-14,2024-01-16,TN,2
4,ORD-1005,Monitor24,"734 MG Road, Chennai (TN)",2024-02-05,2024-02-07,TN,2

In [12]:
#lag Weekend Shipments

df["shipped_on_weekend"] = (df["ship_date"].dt.dayofweek >= 5)

In [13]:
df.head()

,order_id,product_name,ship_address,order_date,ship_date,region_code,days_to_ship,shipped_on_weekend
0,ORD-1001,SmartWatch,"282 MG Road, Chennai (TN)",2024-01-02,2024-01-08,TN,6,False
1,ORD-1002,Monitor24,"105 MG Road, Bengaluru (KA)",2024-01-09,2024-01-15,KA,6,False
2,ORD-1003,Laptop,"33 MG Road, Chennai (TN)",2024-02-07,2024-02-11,TN,4,True
3,ORD-1004,Webcam,"518 MG Road, Chennai (TN)",2024-01-14,2024-01-16,TN,2,False
4,ORD-1005,Monitor24,"734 MG Road, Chennai (TN)",2024-02-05,2024-02-07,TN,2,False