In [1]:
import pandas as pd
df = pd.read_csv("Downloads/sales_data.csv")

In [2]:
df.head()

         Date Region     Category Product  Revenue
0  2024-01-10   East  Electronics  Laptop      500
1  2024-01-15   East    Furniture   Chair      700
2  2024-02-03   West  Electronics   Phone      900
3  2024-02-18  South    Furniture   Table      650
4  2024-03-05  North  Electronics  Laptop      800

In [41]:
pt = pd.pivot_table(df, values = "Revenue", index = "Region", columns = "Category", aggfunc = "sum", fill_value = 0)
print("Revenue by Region × Category")
pt

Revenue by Region × Category

Category  Electronics  Furniture
Region
East             3750       1420
North            2540       1230
South            1940       2890
West             2700       1820

In [43]:
pt1 = pd.pivot_table(df, values = "Revenue", index = "Region", columns = ["Category", "Product"], fill_value = 0)
print("Generl pivot table")
pt1

Generl pivot table

Category Electronics        Furniture
Product       Laptop  Phone     Chair  Table
Region
East      786.666667  695.0     710.0    0.0
North     855.000000  830.0       0.0  615.0
South     970.000000    0.0     735.0  710.0
West        0.000000  900.0     565.0  690.0

In [44]:
df["Date"] = pd.to_datetime(df["Date"])
df.dtypes

Date                 datetime64[ns]
Region                       object
Category                     object
Product                      object
Revenue                       int64
Month                     period[M]
Region_Total                  int64
Percent_of_Region           float64
dtype: object

In [45]:
df["Month"] = df["Date"].dt.to_period("M")
month = df["Month"]

In [46]:
monthly = df.groupby("Month")["Revenue"].sum().reset_index()
monthly

      Month  Revenue
0   2024-01     1200
1   2024-02     1550
2   2024-03     1550
3   2024-04     1500
4   2024-05     1320
5   2024-06     1650
6   2024-07     1550
7   2024-08     1570
8   2024-09      630
9   2024-10      860
10  2024-11      920
11  2024-12      710
12  2025-01     1000
13  2025-02      690
14  2025-03      830
15  2025-04      760

In [47]:
#monthly = df.groupby("Month")["Revenue"].sum().reset_index()
monthly["Running_Total"] = monthly["Revenue"].cumsum()
monthly["Running_Total"]

0      1200
1      2750
2      4300
3      5800
4      7120
5      8770
6     10320
7     11890
8     12520
9     13380
10    14300
11    15010
12    16010
13    16700
14    17530
15    18290
Name: Running_Total, dtype: int64

In [48]:
print("Montly Revenue")
print(monthly)

Montly Revenue
      Month  Revenue  Running_Total
0   2024-01     1200           1200
1   2024-02     1550           2750
2   2024-03     1550           4300
3   2024-04     1500           5800
4   2024-05     1320           7120
5   2024-06     1650           8770
6   2024-07     1550          10320
7   2024-08     1570          11890
8   2024-09      630          12520
9   2024-10      860          13380
10  2024-11      920          14300
11  2024-12      710          15010
12  2025-01     1000          16010
13  2025-02      690          16700
14  2025-03      830          17530
15  2025-04      760          18290

In [55]:
df["Region_Total"] = df.groupby("Region")["Revenue"].transform("sum")
df["Percent_of_Region"] = (df["Revenue"] / df["Region_Total"] * 100).round(2)
print("Percentage of Region Total")
print(df[["Region", "Product", "Revenue", "Percent_of_Region"]])

Percentage of Region Total
   Region Product  Revenue  Percent_of_Region
0    East  Laptop      500               9.67
1    East   Chair      700              13.54
2    West   Phone      900              19.91
3   South   Table      650              13.46
4   North  Laptop      800              21.22
5    East   Phone      750              14.51
6    West   Chair      550              12.17
7   South  Laptop      950              19.67
8   North   Table      600              15.92
9    East   Chair      720              13.93
10   West   Phone      880              19.47
11  South   Table      770              15.94
12  North  Laptop      910              24.14
13   East   Phone      640              12.38
14   West   Chair      580              12.83
15  South  Laptop      990              20.50
16  North   Table      630              16.71
17   East  Laptop      860              16.63
18   West   Phone      920              20.35
19  South   Chair      710              14.70
20   East  Laptop     1000              19.34
21   West   Table      690              15.27
22  North   Phone      830              22.02
23  South   Chair      760              15.73

In [59]:
monthly_region = (df.groupby(["Region", "Month"])["Revenue"].sum().reset_index())

monthly_region = monthly_region.sort_values(["Region", "Month"])

monthly_region["Rolling_Avg"] = (monthly_region.groupby("Region")["Revenue"]
                                 .rolling(window=3, min_periods=1).mean()
                                 .reset_index(level=0, drop=True))

In [61]:
print("3-Month Rolling Average Revenue per Region")
print(monthly_region)

3-Month Rolling Average Revenue per Region
   Region    Month  Revenue  Rolling_Avg
0    East  2024-01     1200  1200.000000
1    East  2024-03      750   975.000000
2    East  2024-05      720   890.000000
3    East  2024-07      640   703.333333
4    East  2024-10      860   740.000000
5    East  2025-01     1000   833.333333
6   North  2024-03      800   800.000000
7   North  2024-05      600   700.000000
8   North  2024-07      910   770.000000
9   North  2024-09      630   713.333333
10  North  2025-03      830   790.000000
11  South  2024-02      650   650.000000
12  South  2024-04      950   800.000000
13  South  2024-06      770   790.000000
14  South  2024-08      990   903.333333
15  South  2024-12      710   823.333333
16  South  2025-04      760   820.000000
17   West  2024-02      900   900.000000
18   West  2024-04      550   725.000000
19   West  2024-06      880   776.666667
20   West  2024-08      580   670.000000
21   West  2024-11      920   793.333333
22   West  2025-02      690   730.000000