In [3]:
import pandas as pd
order = pd.read_csv("Downloads/orders.csv")
cust = pd.read_csv("Downloads/customers.csv")
prdt = pd.read_csv("Downloads/products.csv")
mr = pd.read_csv("Downloads/monthly_revenue.csv")

In [8]:
df1, df2, df3, df4 = order, cust, prdt, mr

In [9]:
df1.head()

  OrderID CustomerID ProductID  Quantity
0      O1      C1978       P40         4
1      O2      C1877       P12         4
2      O3      C1161       P36         1
3      O4      C1379       P45         3
4      O5      C1992       P23         2

In [10]:
df2.head()

  CustomerID CustomerName       City
0      C1000   Customer_0      Delhi
1      C1001   Customer_1     Mumbai
2      C1002   Customer_2  Hyderabad
3      C1003   Customer_3     Mumbai
4      C1004   Customer_4     Mumbai

In [11]:
df3.head()

  ProductID ProductName     Category  Price
0        P1   Product_1  Electronics    674
1        P2   Product_2  Electronics    617
2        P3   Product_3     Clothing   3800
3        P4   Product_4    Furniture   1154
4        P5   Product_5  Electronics   1405

In [12]:
df4.head()

  Month  North  South  East  West
0   Jan  10000   9000  7000  6500
1   Feb  12000   8500  7600  7100
2   Mar  11000  10000  8100  7800
3   Apr  15000   9500  8300  8000
4   May  16000  12000  8800  8400

In [14]:
orders_products = pd.merge(
    df1,
    df3,
    on="ProductID",
    how="inner"
)
orders_products

     OrderID CustomerID ProductID  Quantity ProductName     Category  Price
0         O1      C1978       P40         4  Product_40    Furniture   3695
1         O2      C1877       P12         4  Product_12    Furniture   4957
2         O3      C1161       P36         1  Product_36  Electronics   3576
3         O4      C1379       P45         3  Product_45    Furniture   2361
4         O5      C1992       P23         2  Product_23    Furniture   4622
...      ...        ...       ...       ...         ...          ...    ...
1195   O1196      CX195        P9         3   Product_9    Furniture   3772
1196   O1197      CX196       P38         4  Product_38  Electronics   1700
1197   O1198      CX197       P50         2  Product_50    Furniture   1681
1198   O1199      CX198        P6         5   Product_6     Clothing   4959
1199   O1200      CX199       P19         4  Product_19  Electronics   4443

[1200 rows x 7 columns]

In [15]:
final_df = pd.merge(
    orders_products,
    df2,
    on="CustomerID",
    how="inner"
)

print(final_df.head())

print("Shape :", final_df.shape)

  OrderID CustomerID ProductID  Quantity ProductName     Category  Price  \
0      O1      C1978       P40         4  Product_40    Furniture   3695
1      O2      C1877       P12         4  Product_12    Furniture   4957
2      O3      C1161       P36         1  Product_36  Electronics   3576
3      O4      C1379       P45         3  Product_45    Furniture   2361
4      O5      C1992       P23         2  Product_23    Furniture   4622

   CustomerName       City
0  Customer_978  Hyderabad
1  Customer_877  Bangalore
2  Customer_161    Chennai
3  Customer_379     Mumbai
4  Customer_992      Delhi
Shape : (1000, 9)

In [17]:
#Validate No Rows Lost on Inner Join

print("Original Orders :", len(df1))
print("Rows After Inner Join :", len(final_df))

rows_lost = len(df1) - len(final_df)

print("Rows Lost :", rows_lost)

Original Orders : 1200
Rows After Inner Join : 1000
Rows Lost : 200

In [18]:
df4

  Month  North  South  East  West
0   Jan  10000   9000  7000  6500
1   Feb  12000   8500  7600  7100
2   Mar  11000  10000  8100  7800
3   Apr  15000   9500  8300  8000
4   May  16000  12000  8800  8400
5   Jun  14000  11500  9000  8600

In [22]:
long_df =  df4.melt(
    id_vars = "Month",
    var_name = "Region",
    value_name = "Revenue",
    ignore_index = True
)
long_df

   Month Region  Revenue
0    Jan  North    10000
1    Feb  North    12000
2    Mar  North    11000
3    Apr  North    15000
4    May  North    16000
5    Jun  North    14000
6    Jan  South     9000
7    Feb  South     8500
8    Mar  South    10000
9    Apr  South     9500
10   May  South    12000
11   Jun  South    11500
12   Jan   East     7000
13   Feb   East     7600
14   Mar   East     8100
15   Apr   East     8300
16   May   East     8800
17   Jun   East     9000
18   Jan   West     6500
19   Feb   West     7100
20   Mar   West     7800
21   Apr   West     8000
22   May   West     8400
23   Jun   West     8600

In [23]:
#Orders with No Matching Customer

left_join = pd.merge(
    df1,
    df2,
    on="CustomerID",
    how="left",
    indicator=True
)

left_join

,OrderID,CustomerID,ProductID,Quantity,CustomerName,City,_merge
0,O1,C1978,P40,4,Customer_978,Hyderabad,both
1,O2,C1877,P12,4,Customer_877,Bangalore,both
2,O3,C1161,P36,1,Customer_161,Chennai,both
3,O4,C1379,P45,3,Customer_379,Mumbai,both
4,O5,C1992,P23,2,Customer_992,Delhi,both
...,...,...,...,...,...,...,...
1195,O1196,CX195,P9,3,NaN,NaN,left_only
1196,O1197,CX196,P38,4,NaN,NaN,left_only
1197,O1198,CX197,P50,2,NaN,NaN,left_only
1198,O1199,CX198,P6,5,NaN,NaN,left_only
1199,O1200,CX199,P19,4,NaN,NaN,left_only

In [25]:
missing_customers = left_join[left_join["_merge"] == "left_only"]
missing_customers.count()

OrderID         200
CustomerID      200
ProductID       200
Quantity        200
CustomerName      0
City              0
_merge          200
dtype: int64

In [26]:
print("Orders Without Matching Customer :")
print(missing_customers.head())

print("Total Missing Customers :", len(missing_customers))

Orders Without Matching Customer :
     OrderID CustomerID ProductID  Quantity CustomerName City     _merge
1000   O1001        CX0       P43         4          NaN  NaN  left_only
1001   O1002        CX1       P21         1          NaN  NaN  left_only
1002   O1003        CX2        P4         5          NaN  NaN  left_only
1003   O1004        CX3       P50         5          NaN  NaN  left_only
1004   O1005        CX4       P33         2          NaN  NaN  left_only
Total Missing Customers : 200